apiVersion: apps/v1
kind: Deployment
metadata:
  name: rss-site
  labels:
    owner: me
    environment: prod
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      namespace: test
      labels:
        app: web
    spec:
      dnsPolicy: Default
      containers:
        - name: front-end
          image: nginx:latest
          ports:
            - containerPort: 80
      nodeSelector:
        disktype: ssd         
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
