run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    # Defaults
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - varcheck

    # Extras
    - gofmt
    - goimports
