apiVersion: apps/v1
kind: Deployment
metadata:
  name: pass-RollingUpdate & RevisionHistoryLimit
  labels:
    app: test
spec:
  revisionHistoryLimit: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
        version: v2.0.0
