---
apiVersion: apps/v1
kind: Version
metadata:
  name: fail-version-policy
  labels:
    Version: '1'
    environment: qa
    app: test
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
---
apiVersion: apps/v1
kind: Pod
metadata:
  name: fail-version-policy-checker
  labels:
  Inspection: 'false'
    environment: prod
    app: test
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
