---
apiVersion: apps/v1
kind: Pod
metadata:
  name: version-policy
  labels:
    Version: '1.0'
    environment: prod
    app: web
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
apiVersion: apps/v1
kind: Pod
metadata:
  name: version-policy-checker
  labels:
    Inspection: 'false'
    environment: prod
    app: web
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
