---
apiVersion: apps/v1
kind: Service
metadata:
  name: fail-user-permission
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
---
apiVersion: apps/v1
kind: Pod
metadata:
  name: fail-group-permission
spec:
  securityContext:
    allowPrivilegeEscalation: false
    runAsUser: 0
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
---
apiVersion: apps/v1
kind: Pod
metadata:
  name: fail-privilege-escalation
spec:
  securityContext:
    runAsGroup: 1000
    runAsUser: 1000
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
---
apiVersion: apps/v1
kind: PodSecurityPolicy
metadata:
  name: fail-deprecated
spec:
  securityContext:
    runAsGroup: 1000
    runAsUser: 0
    allowPrivilegeEscalation: true
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Pod
metadata:
  name: fail-flex-volume
spec:
  securityContext:
    runAsGroup: 1000
    runAsUser: 1000
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
  allowedFlexVolumes:
    - driver: example/cifs
    