---
apiVersion: apps/v1
kind: Pod
metadata:
  name: fail-user-permission
spec:
  securityContext:
    runAsUser: 11000
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
---
apiVersion: apps/v1
kind: Pod
metadata:
  name: fail-group-permission
spec:
  securityContext:
    allowPrivilegeEscalation: false
    runAsUser: 0
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
---
apiVersion: apps/v1
kind: Pod
metadata:
  name: fail-privilege-escalation
spec:
  securityContext:
    runAsGroup: 1000
    runAsUser: 1000
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
