---
apiVersion: apps/v1
kind: Pod
metadata:
  name: pass-security
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: false
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
