---
apiVersion: v1
kind: Pod
metadata:
  name: fail-resource-quotas-for-pod
  labels:
    environment: prod
    app: test
    owner: test-at-datree.io
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: "175m"
          memory: "768Mi"
        limits:
          cpu: "750m"
          memory: "3072Mi"
      securityContext:
        readOnlyRootFilesystem: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fail-resource-quotas-for-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "175m"
              memory: "768Mi"
            limits:
              cpu: "750m"
              memory: "3072Mi"
          securityContext:
            readOnlyRootFilesystem: true
