---
apiVersion: apps/v1
kind: Pod
metadata:
  name: pass-security
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    readOnlyRootFilesystem: false
    allowPrivilegeEscalation: false
    privileged: false
    allowedProcMountTypes: DefaultProcMount
  volumes:
    - flexVolume
  allowedFlexVolumes:
    - driver: example/lvm
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
