---
apiVersion: apps/v1
kind: Pod
metadata:
  labels:
    environment: qa
    app: test
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
---
apiVersion: apps/v1
kind: Pod
metadata:
  labels:
    environment: prod
    app: test
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
---
apiVersion: apps/v1
kind: Pod
metadata:
  labels:
    environment: prod
    app: test
    owner: test@datree.io
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
