---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-with-ttl
spec:
  template:
    spec:
      containers:
      - name: myjob
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never