---
apiVersion: apps/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fail-namespace
spec:
  minReplicas: 1
  maxReplicas: 10
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
---
apiVersion: apps/v1
kind: HorizontalPodAutoscaler 
metadata:
  name: fail-max-replicas
  namespace: fail
spec:
  minReplicas: 1
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
---
apiVersion: apps/v1
kind: HorizontalPodAutoscaler 
metadata:
  name: fail-min-replicas
  namespace: fail
spec:
  maxReplicas: 10
  minReplicas: 0 
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
