---
apiVersion: apps/v1
kind: HorizontalPodAutoscaler 
metadata:
  name: pass-policy
spec:
  maxReplicas: 10
  minReplicas: 1
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  targetCPUUtilizationPercentage: 50
  scaleTargetRef:
    apiVersion: 1
    kind: Deployment
    name: pass-ref
