---
 apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: Fail-PodDisruptionBudgetMinAvailable
spec:
  minAvailable: NA
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: Fail-PodDisruptionBudgetMaxUnavailable
spec:
  maxUnvailable: NA
---