---
apiVersion: apps/v1
kind: PodDisruptionBudget
metadata:
  name: pass-PodDisruptionBudgetMinAvailable
spec:
  minAvailable: 2
---
apiVersion: apps/v1
kind: PodDisruptionBudget
metadata:
  name: pass-PodDisruptionBudgetMaxUnavailable
spec:
  maxUnavailable: 1
#If One Policy Passes the Other Fails