apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    environment: prod
spec:
  shareProcessNamespace: true
  securityContext:
    runAsUser: 0
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "1300m"
    securityContext:
      privileged: true
  - name: app
    image: asia.gcr.io/myproject/app:v3
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "300m"
    securityContext:
      allowPrivilegeEscalation: true
  - name: app2
    image: asia.gcr.io/myproject/app2:v3
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "300m"
    securityContext:
      allowPrivilegeEscalation: false
  - name: app3
    image: asia.gcr.io/myproject/app3:v3
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "300m"
    securityContext:
      allowPrivilegeEscalation: false
