apiVersion: apps/v1
kind: Pod
schema:
  metadata:
    name: pass-policy
    labels:
      owner: me
      size: g3.k3s.large
      app: web
  spec:
    containers:
    - name: nginx
      image: nginx:1.14.2
      securityContext: 
        runAsGroup: 3000
      ports:
      - containerPort: 80
