---
apiVersion: apps/v1
kind: Pod
metadata:
  name: pass-policy
  labels:
    environment: qq
    app: me@test.com
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
