apiVersion: apps/v1
kind: Pod
metadata:
  name: pass-policy
  labels:
    owner: me
    instances: 4
    app: web
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
