apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollingupdate-strategy
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: web-app-rollingupdate-strategy
      version: nanoserver-1809
  replicas: 3
  template:
    metadata:
      labels:
        app: web-app-rollingupdate-strategy
    spec:
      containers:
        - name: web-app-rollingupdate-strategy
          image: hello-world:nanoserver-1809