name: Check commit messages
on: pull_request
jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
      - name: check commit messages
        run: python ./scripts/check_commit_messages.py
