name: PR title
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.8'
      - name: check PR title
        run: python ./scripts/check_pr_title.py
