---
apiVersion: apps/v1
kind: Pod
metadata:
  name: pass-policy
  labels:
    owner: me
    environment: prod
    app: web
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    containerstate: Running
    ports:
    - containerPort: 80